# This program will process each tsv files in the passed directory (non-recursively) generated by HTSeq-count,
# and generate a normalized count data table as output.
# The normalized count data table is generated using the DESeq2 package with recommended settings

suppressPackageStartupMessages({
  library(dplyr)
  library(DESeq2)
})
  
# gene_filtered_files         <- snakemake@input[["gene_filtered_files"]],
# transcript_filtered_files   <- snakemake@input[["transcript_filtered_files"]]
# gene_normalized_counts      <- snakemake@output[["gene_normalized_files"]],
# transcript_normalized_files <- snakemake@output[["transcript__normalized_files"]]
# threads                     <- snakemake@params[["sub_threads"]]

gene_filtered_files <- "results/Counts/9606/gene_count.tsv"
transcript_filtered_files <- "results/Counts/9606/transcript_count.tsv"
gene_normalized_files <- "results/Counts/9606/gene_normalized.tsv"
transcript_normalized_files <- "results/Counts/9606/transcript_normalized.tsv"
threads = 10

makeSampleTable <- function(count_file) {
  logger::log_debug("Generating sample table from:\n", count_file)
  file_name <- basename(count_file) 
  sample_name <- paste(
    dirname(count_file) %>% basename,
    tools::file_path_sans_ext(count_file) %>% basename,
    sep = "_"
  ) %>%
    gsub(pattern = "\\_count", replacement = "s")
  sample_condition <- sub(
    pattern = "(.*\\.tsv)",
    replacement = "\\1", x = count_file
  )
  
  data.frame(
    sampleName = sample_name,
    fileName = file_name,
    condition = sample_condition
  )
}


makeDESeqObject <- function(sample_table, count_file) {
  browser()
  logger::log_debug("Generating DESeq2 object")
  DESeqDataSetFromHTSeqCount(
    sampleTable = sample_table, directory = dirname(count_file), design= ~ condition
  )
}

performNormalization <- function(deseq_object) {
  browser()
  logger::log_debug("Perform DESeq2 normalization")
  dds <- DESeq(object = deseq_object)
  counts(object = dds, normalized = TRUE)
}
 
normalizeSamples <- function(count_file, normalized_file) {
  logger::log_info("Normalizating with DESeq for:\n", count_file)
  sample_table <- makeSampleTable(count_file)
  deseq_object <- makeDESeqObject(sample_table, count_file)
  normalized <- performNormalization(deseq_object)
  
  logger::log_info("Writing normalized matrix to :\n", normalized_file)
  write.table(x = normalized, file = normalized_file, quote = FALSE)
}


invisible({
  files <- c(gene_filtered_files, transcript_counts_files)
  mclapply(X = seq_along(files), mc.cores = threads, FUN = function(i) {
    count_file <- gene_filtered_files[i]
    normalized_file <- gene_normalized_files[i]
    
    normalizeSamples(count_file, normalized_file)
    TRUE
  })
  
  parallel::mclapply(X = seq_along(transcript_filtered_files), mc.cores = threads, FUN = function(i) {
    count_file <- transcript_filtered_files[i]
    normalized_file <- transcript_normalized_files[i]
    
    normalizeSamples(count_file, normalized_file)
    TRUE
  })
})

