email: xxx@gmail.com # For Eutils -> if they ban your IP, they will warn yoou by email
taxids: taxids.tx
samples: samples.txt
ensembl_release: 102
prefetch: prefetch
fastq_dump: fastq-dump
star: STAR
samtools_sort: samtools sort
htseq_count: htseq-count
ref_dir: /disk2/Resources/seqDB/ensembl/release-100/
parallel: 6
sub_threads: 8
threshold: 0.75
strandedness: no
output_dir: /disk3/Data/RNAseq/dev20.004_LiverDB/Results/