prefetch: prefetch
fastq_dump: fastq-dump
star: STAR
samtools_sort: samtools sort
htseq_count: htseq-count
ref_dir: /disk2/Resources/seqDB/ensembl/release-100/
max_threads: 36
sub_threads: 8
threshold: 0.75
strandedness: no
workdir: ../
output_dir: /disk3/Data/RNAseq/dev20.004_LiverDB/
species:
  - 9606
samples:
  - SRR1045522
  - SRR1045523
  - SRR1045524
  - SRR1045525
  - SRR1045526
  - SRR1045527
  - SRR5750514
  - SRR5750521